# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options


before_script:
  - echo "Running Build"
   
after_script:
  - echo "After script section"

stages:
  - dependencycheck
  - test
  - analyze
  - build
  - deploy
  - document

dependency:
  stage: dependencycheck
  script:
      - powershell.exe -command "if(!(Get-Module PSdepend)) {Install-Module PSDepend -force}"
      - powershell.exe -command "if(!(Get-Module buildhelpers)){Install-Module buildhelpers -force}"
      - powershell.exe -command "if(!(Get-Module pester)){Install-Module pester -force}"
      - powershell.exe -command "if(!(Get-Module PSScriptAnalyzer)){Install-Module PSScriptAnalyzer -force}"
      - powershell.exe -command "if(!(Get-Module psake)){Install-Module psake -force}"
      - powershell.exe -command "if(!(Get-Module PlatyPS)){Install-Module PlatyPS -force}"

Tests:
  stage: test
  script:
    - powershell.exe -command "if ((Invoke-Pester -Script .\functions\*.ps1 -passthru -show all -OutputFile .\testResults.xml -OutputFormat NUnitXml).FailedCount -gt 0){Throw 'Unit Tests Failed'}"
  artifacts:
    paths:
     - testResults.xml

Analyze:
  stage: analyze
  script:
    - powershell.exe -file ".\build\4.Analyze.ps1"

build:
  stage: build
  script:
    - powershell.exe -file .\build\0.build.ps1
  artifacts:
    paths:
      - passwordstate-management
  only:
    - master

Nuget:
  stage: deploy
  script:
    - powershell.exe -file .\build\3.deploy.ps1 -repotype $($env:repotype) -apikey $($env:apikey) -reponame $($env:reponame) -SourceLocation $($env:SourceLocation) -PublishLocation $($env:publishLocation)
  only:
    - master

.UpdateDocumentation:
  stage: document
  script:
    - powershell.exe -command "Update-MarkdownHelp -Path .\docs"
  only:
    - master